# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('href', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
